{
	"_Type": "Action.Type.ODataService.DeleteEntity",
	"ActionResult": {
		"_Name": "Mitigations_DeleteEntity"
	},
	"OnFailure": "/RiskManagementApp/Actions/DeleteMitigationsEntityFailureMessage.action",
	"OnSuccess": "/RiskManagementApp/Actions/CloseModalPage_Complete.action",
	"Target": {
		"Service": "/RiskManagementApp/Services/myapp_mdk_demo.service",
		"EntitySet": "Mitigations",
		"ReadLink": "{@odata.readLink}"
	}
}