{
	"_Type": "Action.Type.ODataService.UpdateEntity",
	"ActionResult": {
		"_Name": "Mitigations_UpdateEntity"
	},
	"OnFailure": "/RiskManagementApp/Actions/UpdateMitigationsEntityFailureMessage.action",
	"OnSuccess": "/RiskManagementApp/Actions/CloseModalPage_Complete.action",
	"Target": {
		"Service": "/RiskManagementApp/Services/myapp_mdk_demo.service",
		"EntitySet": "Mitigations",
		"ReadLink": "{@odata.readLink}"
	},
	"Properties": {
		"description": "#Control:MitigationsEdit_Description/#Value",
		"owner": "#Control:MitigationsEdit_Owner/#Value",
		"timeline": "#Control:MitigationsEdit_Timeline/#Value"
	}
}